### ISSUE TITLE
update Tailwind version

### ISSUE THREAD

**Issue by core45** [laravel-frontend-presets/tall#108]
This package installs Tailwind v.2. Needs to be updated to v.3

**Comment by danharrin** [comment]
Fixed by #98.

**Comment by core45** [comment]
I updated all packages in my Laravel and it's still Tailwind 2.
I even did php artisan ui tall and it's still the same. 
It is not upgrading to Tailwind v.3
